# -*- coding: utf-8 -*-
"""Data_cleaning_and_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qIZt3ZYl9LBj-eu4WklMox4NJTeP8tlX
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('/content/sample_data/california_housing_train.csv')
df.head()
df.info()
df.describe()
df.isnull().sum()
df = df.fillna(df.mean(numeric_only=True))
df.duplicated().sum()
df.drop_duplicates(inplace=True)
df.describe()
df['income_category'] = pd.cut(
    df['median_income'],
    bins=[0,2,4,6,8,15],
    labels=['Low','Medium','High','Very High','Rich']
)
correlation = df.corr(numeric_only=True)

print(correlation)
plt.figure(figsize=(10, 8))
sns.heatmap(correlation, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.xlabel("House Value")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(8,5))

sns.scatterplot(
    x='median_income',
    y='median_house_value',
    data=df
)

plt.title("Income vs House Value")

plt.show()

plt.figure(figsize=(12,8))

sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')

plt.title("Correlation Heatmap")

plt.show()

sns.barplot(
    x='income_category',
    y='median_house_value',
    data=df
)

plt.title("House Value by Income Category")

plt.show()