# -*- coding: utf-8 -*-
"""exploratory_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xItuZyDVKTf8dBuAxfCZSbwZFKXMQCaM
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('/content/sample_data/california_housing_train.csv')
df.head()
df.info()
df.describe()
df.isnull().sum()
df = df.fillna(df.mean())
correlation = df.corr()

print(correlation)
plt.figure(figsize=(12,8))

sns.heatmap(df.corr(), annot=True, cmap='coolwarm')

plt.title("Correlation Heatmap")

plt.show()
plt.figure(figsize=(8,5))

sns.histplot(df['median_house_value'], bins=30)

plt.title("Distribution of House Prices")

plt.show()
plt.figure(figsize=(8,5))

sns.scatterplot(
    x='median_income',
    y='median_house_value',
    data=df
)

plt.title("Income vs House Value")

plt.show()
plt.figure(figsize=(8,5))

sns.boxplot(x=df['median_house_value'])

plt.title("Boxplot of House Prices")

plt.show()