# -*- coding: utf-8 -*-
"""real-world_data_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZDw1ieH8m87wEp2wj5-0Xhmjs3SCIwr
"""

# python
# ============================================
# REAL-WORLD DATA SCIENCE PROJECT
# RETAIL SALES DATA ANALYSIS & PREDICTION
# ============================================

# --------------------------------------------
# STEP 1: IMPORT LIBRARIES
# --------------------------------------------

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

# --------------------------------------------
# STEP 2: LOAD DATASET
# --------------------------------------------

# Replace 'superstore.csv' with your dataset file name

df = pd.read_csv('train.csv')

# --------------------------------------------
# STEP 3: VIEW DATASET
# --------------------------------------------

print("FIRST 5 ROWS")
print(df.head())

print("\nDATASET INFORMATION")
print(df.info())

print("\nSTATISTICAL SUMMARY")
print(df.describe())

# --------------------------------------------
# STEP 4: CHECK MISSING VALUES
# --------------------------------------------

print("\nMISSING VALUES")
print(df.isnull().sum())

# Fill missing values

df.fillna(0, inplace=True)

# --------------------------------------------
# STEP 5: REMOVE DUPLICATES
# --------------------------------------------

print("\nDUPLICATE ROWS:", df.duplicated().sum())

df.drop_duplicates(inplace=True)

# --------------------------------------------
# STEP 6: CONVERT DATE COLUMN
# --------------------------------------------

df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y')

# Extract month and year

df['Month'] = df['Order Date'].dt.month
df['Year'] = df['Order Date'].dt.year

# --------------------------------------------
# STEP 7: SALES ANALYSIS
# --------------------------------------------

# Total Sales by Category

category_sales = df.groupby('Category')['Sales'].sum()

print("\nTOTAL SALES BY CATEGORY")
print(category_sales)

# --------------------------------------------
# STEP 8: VISUALIZATION
# --------------------------------------------

# -----------------------------
# SALES BY CATEGORY
# -----------------------------

plt.figure(figsize=(8,5))

category_sales.plot(kind='bar')

plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Total Sales")

plt.show()

# -----------------------------
# MONTHLY SALES TREND
# -----------------------------

monthly_sales = df.groupby('Month')['Sales'].sum()

plt.figure(figsize=(8,5))

monthly_sales.plot(kind='line', marker='o')

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")

plt.show()

# -----------------------------
# CORRELATION HEATMAP
# -----------------------------

plt.figure(figsize=(10,6))

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")

plt.show()

# --------------------------------------------
# STEP 9: MACHINE LEARNING
# --------------------------------------------

# Feature Selection

X = df[['Postal Code']]

# Target Variable

y = df['Sales']

# Split Training and Testing Data

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Create Model

model = LinearRegression()

# Train Model

model.fit(X_train, y_train)

# Make Predictions

y_pred = model.predict(X_test)

# --------------------------------------------
# STEP 10: MODEL EVALUATION
# --------------------------------------------

mae = mean_absolute_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("\nMODEL PERFORMANCE")

print("Mean Absolute Error:", mae)

print("R2 Score:", r2)

# --------------------------------------------
# STEP 11: ACTUAL VS PREDICTED GRAPH
# --------------------------------------------

plt.figure(figsize=(8,5))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Sales")
plt.ylabel("Predicted Sales")

plt.title("Actual vs Predicted Sales")

plt.show()

# --------------------------------------------
# STEP 12: FINAL INSIGHTS
# --------------------------------------------

print("\nPROJECT INSIGHTS")

print("""
1. Certain product categories generated higher sales.

2. Some regions produced more profit than others.  <-- Note: This insight is now based on other data, as 'Profit' column was removed.

3. Monthly sales trends showed variations across the year.

4. Correlation analysis revealed relationships between sales and available numerical features (e.g., Postal Code, Month, Year).

5. Machine learning model successfully predicted sales using Postal Code.
""")

# --------------------------------------------
# STEP 13: CONCLUSION
# --------------------------------------------

print("""
CONCLUSION:

This project analyzed a real-world retail sales dataset using
data cleaning, exploratory data analysis, visualization,
and machine learning techniques.

The analysis helped identify important sales trends,
profit patterns, and relationships between variables.
A Linear Regression model was also used to predict sales outcomes.
""")